[log]
LEVEL = "INFO"
PATH = "/home/logs/x-test.log"
STDOUT = true
ROTATION = "00:00"
RETENTION = "30 days"

[service]
# schema swagger
INCLUDE_IN_SCHEMA = true
SOCKET_IO_ON = true

[socket_io]
SOCKET_IO_NAMESPACES = ["/message"]
SOCKET_IO_MOUNT = "/"
