version: '3.9'
services:
  sockets:
    container_name: fastapi_sockets
    build: ./fastapi_sockets
    restart: always
    environment:
      TZ: Asia/Shanghai
    command: /bin/bash ./docker-entrypoint.sh
    volumes:
      - ./fastapi_sockets:/home/project
      - ./conf/sockets/product.local.toml:/home/project/conf/product.local.toml
      - ./logs/sockets:/home/logs
    networks:
      fastapi_tm_net:
        ipv4_address: "172.22.0.5"

networks:
  fastapi_tm_net:
      external: true
